### ISSUE TITLE
400 bad request, token_not_provided from JWT 

### ISSUE THREAD

**Issue by coding-sunshine** [layer7be/vue-starter-laravel-api#1]
I ran into an issue where No matter what I do I'm getting 400 bad request, token_not_provided from JWT Auth.. Spent a lot of time on solving this, It turns out apache removes the authorization header by default. (Not sure why?). By dropping the following in your .htaccess file in your public folder fixes the issue:

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

**Comment by coding-sunshine** [comment]
I have already solved the issue, but for the record that if anyone else runs into same issue they know the solution. You can close the issue :)

**Comment by kcalliauw** [comment]
This has now been added to the README. Thanks for reporting the issue.

**Comment by w00p** [comment]
For information, I had to use the following in .htaccess

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

Notice the stars *

**Comment by askaoru** [comment]
@kcalliauw , you may want to update the readme again. I had the same problem and @w00p 's code works for me.

**Comment by lmichailian** [comment]
I use php artisan serve and have same problem my .httaccess
`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header

    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
</IfModule>`
