### ISSUE TITLE
Refreshing the page forces to login again

### ISSUE THREAD

**Issue by rajabishek** [layer7be/vue-starter-laravel-api#11]
On refreshing the page for lets say 2-3 times it is forcing to login again ( token is getting blacklisted ). I am not sure why is this happening ?
<img width="1280" alt="refresh token invalid" src="https://cloud.githubusercontent.com/assets/6145125/11762164/a24cab10-a104-11e5-88fd-e61f54497bd8.png">

**Comment by raditv** [comment]
you should comment blacklist mode enabled or set it to disabled on jwt config file. otherwise you should check on vue side code, because the token need to be refreshed on everyrequest when blacklist mode enabled.

**Comment by kcalliauw** [comment]
There have been some changes to the backend code. Kindly test again and let me know if this is still an issue for you.
