### ISSUE TITLE
Double token validation not required ?

### ISSUE THREAD

**Issue by rajabishek** [layer7be/vue-starter-laravel-api#12]
The jwt.refresh middleware is already ruuning before all the endpoints that are managed by DogsController. Then when is the jwt.auth middleware applied in the DogsController ?

public function __construct() 
{
    $this->middleware('jwt.auth');
}

This is not required as jwt.refresh middleware is already validating the tokens.

**Comment by kcalliauw** [comment]
For some reason with Laravel 5.2 I had to switch from jwt.refresh to jwt.auth globally in the routes file. This should now no longer be an issue.
