### ISSUE TITLE
Fatal error: Class 'Illuminate\Foundation\Application' not found

### ISSUE THREAD

**Issue by kayyyy** [layer7be/vue-starter-laravel-api#17]
On a fresh git clone you cant do `composer install`
```
vue-starter-laravel-api [master] composer install
> php artisan clear-compiled

Fatal error: Class 'Illuminate\Foundation\Application' not found in /Users/bob/Desktop/code/vue-starter-laravel-api/bootstrap/app.php on line 14
```

**Comment by iannazzi** [comment]
Thats odd.... I have not had this issue... You can remove `php artisan clear-compile` from `composer.json` and try composer install again.

**Comment by kcalliauw** [comment]
For me ```composer install``` also complained about not yet finding the vendor folder. I just committed a release with some fixes. in the pre-update-cmd of composer.json I commented the clear-compiled phase. I don't know how to explicitly not do this when doing an install only, but it seems to mitigate the issue for now. If anybody has an idea on how to avoid clear-compiled on install only, please let me know.
